pipelines:
  default:
    - step:
        name: Build and test
        image: tobiassundgrencollector/elm-build-target:v6 # The image is build using the dockerfile in the docker folder and then published to docker hub 
        script:
          - elm make ./src/Main.elm
          - elm-test --fuzz 40
        artifacts:
          - index.html
    - step:
        name: Deploy to staging (uat)
        deployment: staging
        trigger: manual
        script:
          - curl --ftp-ssl -T "index.html" -k -u "$ftpuser_uat"":""$ftppassword_uat" "$ftpurl_uat"
    - step:
        name: Deploy to prod
        deployment: production
        trigger: manual
        script:
          - curl --ftp-ssl -T "index.html" -k -u "$ftpuser_prod"":""$ftppassword_prod" "$ftpurl_prod"
